services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: apex-ci4
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    network_mode: host
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: apex-redis
    command: ["redis-server", "--port", "6380"]
    restart: unless-stopped

