<?php
namespace App\Controllers\Admin\V1;

use App\Libraries\ApiResponse;
use App\Controllers\BaseController;
use App\Traits\Crud\EntityListTrait;

/**
 * Generated by app:make:controller
 * - Extends BaseController
 * - Entity: \App\Entities\Course_mapping
 * - Slug: course_mapping
 */
class CourseMappingController extends BaseController
{
    use EntityListTrait;
    public function index()
    {
        $payload = $this->listApiEntity('course_mapping');
        return ApiResponse::success(data: $payload);
    }

    public function show(int $id)
    {
        $payload = $this->showListEntity('course_mapping', $id);
        return ApiResponse::success(data: $payload);
    }

    /**
     * @throws \Throwable
     */
    public function create()
    {
        $entity  = new \App\Entities\Course_mapping();
        $payload = $this->request->getPost();

        $row = $entity->insertSingle(
            $payload ?? [],
            $this->request->getFiles() ?? []
        );

        if (!$row) {
            return ApiResponse::error("Unable to create course mapping");
        }

        return ApiResponse::success('Course mapping inserted successfully', $payload);
    }

    /**
     * @throws \Throwable
     */
    public function update(int $id)
    {
        $entity  = new \App\Entities\Course_mapping();
        $payload = $this->request->getRawInput();

        $row = $entity->updateSingle(
            $id,
            $payload ?? []
        );

        if (!$row) {
            return ApiResponse::error("Unable to update course mapping");
        }

        return ApiResponse::success('Course mapping updated successfully', $payload);
    }

    /**
     * @throws \Throwable
     */
    public function delete(int $id)
    {
        $entity = new \App\Entities\Course_mapping();

        $row = $entity->deleteSingle($id);
        if (!$row) {
            return ApiResponse::error("Unable to delete course mapping");
        }

        return ApiResponse::success('Course mapping deleted successfully');
    }
}
